name: Build Wishlist JSON

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04

    env:
      STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run fetch script
        run: python fetch.py

      - name: Commit JSON if exists
        run: |
          if [ -f wishlist_sale_under_1000.json ]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add wishlist_sale_under_1000.json
            git commit -m "Update wishlist JSON" || echo "No changes"
            git push
          else
            echo "JSON file not generated. Skipping commit."
          fi
